print("File handling in python :\n")

#f=open("myfile.txt","a+")
#f.write("Hey akshay awesome man!")
#f.write("\n Yes i know that")
#data=f.read()
#print(data)
#f.close()

file=open("akshay's-python.txt","r")
#data=file.write("Hey! where do you see your self in next 5 years ?")
#print(data)
#data=file.write("\nI see myself on the top!")
#print(data)
#data=file.read()
#data=file.readline()
data=file.readlines()
print(data)
file.close()
